import './js/all-category.js';
import './js/all-category-favorite.js';
import './js/popular.js';
import './js/hero.js';
import './js/filters.js';
import './js/header.js';
import './js/modal-order.js';
import './js/modal-rating.js';
import './js/modal-recipes.js';
