import './js/all-category.js'
import './js/all-category-favorite.js'
import './js/popular.js'
import './js/swiper.js';
import './js/swiper-api.js';
import './js/filters.js'
import './js/header.js'
import './js/modal-order.js'
import './js/modal-rating.js'
import './js/modal-recipes.js'
import './js/API-request/all-category.js'
import './js/scrollbar.js'